version: '3.8'

services:
  frontend:
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev

  backend:
    volumes:
      - ./api:/app/api
    command: uvicorn api.index:app --host 0.0.0.0 --port 8000 --reload 